/*
 * DIO.h
 *
 *  Created on: Jan 30, 2019
 *      Author: Hanna Nabil
 */
 #ifndef _DIO_CONFIG_H
 #define _DIO_CONFIG_H
 /* comment : Digital channel initial direction 
  Range : DIO_u8_INPUT
  */
  
 #define DIO_U8_PIN0_DIR   DIO_U8_OUTPUT
 #define DIO_U8_PIN1_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN2_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN3_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN4_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN5_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN6_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN7_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN8_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN9_DIR   DIO_U8_INPUT
 #define DIO_U8_PIN10_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN11_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN12_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN13_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN14_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN15_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN16_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN17_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN18_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN19_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN20_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN21_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN22_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN23_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN24_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN25_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN26_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN27_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN28_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN29_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN30_DIR  DIO_U8_INPUT
 #define DIO_U8_PIN31_DIR  DIO_U8_INPUT
 
 
 
 #endif
